using RPGF.Editor.EventSystem.Attributes;
using RPGF.EventSystem;
using RPGF.EventSystem.Attributes;
using System.Reflection;

namespace RPGF.Editor.EventSystem
{
    public class AutoGeneratedNodeBase : EventGraphNodeBase
    {
        public AutoGeneratedNodeBase(ActionBase action) : base(action)
        {
        }

        public override void UIContructor()
        {
            var metaData = action.GetType().GetCustomAttribute<GenerateActionNodeAttribute>();

            if (metaData is not null)
            {
                title = metaData.Label;
                tooltip = metaData.Description;
            }
        }
    }
}
