using RPGF.EventSystem;
using RPGF.EventSystem.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using UnityEditor.UIElements;
using UnityEngine;
using UnityEngine.UIElements;

namespace RPGF.Editor.EventSystem
{
    public class AutoGeneratedNode : EventGraphNodeBase
    {
        public const string IntTypeName = "int";
        public const string StringTypeName = "string";
        public const string FloatTypeName = "float";
        public const string DoubleTypeName = "double";
        public const string DecimalTypeName = "decimal";
        public const string BoolTypeName = "bool";

        private IEnumerable<FieldInfo> publicFields;

        public AutoGeneratedNode(ActionBase action) : base(action)
        {
            var metaData = action.GetType().GetCustomAttribute<GenerateActionNodeAttribute>();

            if (metaData is not null)
            {
                title = metaData.Label;
                tooltip = metaData.Description;
            }

            publicFields = action.GetType().GetFields(BindingFlags.Default | BindingFlags.Public | BindingFlags.Instance)
                                               .Where(f => f.IsPublic && !f.IsStatic && !f.IsInitOnly);
        }

        public override void UIContructor()
        {
            foreach (var field in publicFields)
            {
                VisualElement additingElement = null;

                var options = field.FieldType.GetCustomAttribute<ActionFieldOptionAttribute>();

                string label = options?.Label ?? field.Name;

                switch (field.FieldType.Name)
                {
                    case nameof(String):
                    case StringTypeName:
                        var textField = new TextField(label)
                        {
                            multiline = options?.MultiLine ?? false
                        };
                        textField.SetValueWithoutNotify(field.GetValue(action) as string);
                        textField.RegisterValueChangedCallback(value =>
                        {
                            field.SetValue(action, value.newValue);

                            MakeDirty();
                        });

                        additingElement = textField;
                        break;
                    case nameof(Int16):
                    case nameof(Int32):
                    case nameof(Int64):
                    case IntTypeName:
                        var intField = new IntegerField(label);
                        intField.SetValueWithoutNotify((int)field.GetValue(action));
                        intField.RegisterValueChangedCallback(value =>
                        {
                            field.SetValue(action, value.newValue);

                            MakeDirty();
                        });

                        additingElement = intField;
                        break;
                    case nameof(Double):
                    case nameof(Decimal):
                    case nameof(Single):
                    case FloatTypeName:
                        var floatField = new FloatField(label);
                        floatField.SetValueWithoutNotify((float)field.GetValue(action));
                        floatField.RegisterValueChangedCallback(value =>
                        {
                            field.SetValue(action, value.newValue);

                            MakeDirty();
                        });

                        additingElement = floatField;
                        break;
                    case nameof(Boolean):
                    case BoolTypeName:
                        var toggle = new Toggle(label);
                        toggle.SetValueWithoutNotify((bool)field.GetValue(action));
                        toggle.RegisterValueChangedCallback(value =>
                        {
                            field.SetValue(action, value.newValue);

                            MakeDirty();
                        });

                        additingElement = toggle;
                        break;
                    case nameof(UnityEngine.Object):
                        var objectField = new ObjectField(label)
                        {
                            objectType = field.FieldType,
                            allowSceneObjects = options?.AllowSceneObjects ?? false
                        };
                        objectField.SetValueWithoutNotify(field.GetValue(action) as UnityEngine.Object);
                        objectField.RegisterValueChangedCallback(value =>
                        {
                            field.SetValue(action, value.newValue);

                            MakeDirty();
                        });

                        additingElement = objectField;
                        break;
                    case nameof(Color):
                        var colorField = new ColorField(label);
                        colorField.SetValueWithoutNotify((Color)field.GetValue(action));
                        colorField.RegisterValueChangedCallback(value =>
                        {
                            field.SetValue(action, value.newValue);

                            MakeDirty();
                        });

                        additingElement = colorField;
                        break;
                }

                if (additingElement == null && field.FieldType.BaseType == typeof(Enum))
                {
                    var value = field.GetValue(action) as Enum;

                    var enumField = new EnumField(label, value);
                    enumField.RegisterValueChangedCallback(value =>
                    {
                        field.SetValue(action, value.newValue);

                        MakeDirty();
                    });

                    additingElement = enumField;
                }

                extensionContainer.Add(additingElement);
            }
        }
    }
}
