using RPGF.Editor.EventSystem.Attributes;
using RPGF.EventSystem;
using RPGF.EventSystem.Attributes;
using RPGF.EventSystem.Default;
using RPGF.EventSystem.Graph;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using UnityEditor;
using UnityEditor.Experimental.GraphView;
using UnityEngine;
using UnityEngine.UIElements;

namespace RPGF.Editor.EventSystem
{
    public class EventGraphView : GraphView
    {
        private readonly Type[] _nodeTypes;
        private readonly Type[] _autoNodeTypes;

        private readonly EventGraphWindow _window;

        public GraphEvent Event => _window.Event;

        public readonly Vector2 DefaultNodeSize = new Vector2(300, 400);

        public event Action OnSaved;

        private EventGraphNodeBase[] Nodes => nodes.Select(n => (EventGraphNodeBase)n).ToArray();

        public EventGraphView(EventGraphWindow window)
        {
            SetupZoom(ContentZoomer.DefaultMinScale, ContentZoomer.DefaultMaxScale);

            this.AddManipulator(new ContentDragger());
            this.AddManipulator(new SelectionDragger());
            this.AddManipulator(new RectangleSelector());
            this.AddManipulator(new ContentZoomer());

            var grid = new GridBackground();
            styleSheets.Add(Resources.Load<StyleSheet>("EventGraphViewStyle"));

            _nodeTypes = GetType().Assembly.GetTypes()
                                           .Where(type => type.GetCustomAttribute<UseActionNodeAttribute>() != null 
                                                       && type.BaseType.BaseType != null && type.BaseType.BaseType == typeof(EventGraphNodeBase))
                                           .ToArray();

            _autoNodeTypes = typeof(ActionBase).Assembly.GetTypes()
                                                        .Where(type => type.GetCustomAttribute<GenerateActionNodeAttribute>() != null
                                                                    && type.BaseType == typeof(ActionBase))
                                                        .ToArray();

            Insert(0, grid);

            grid.StretchToParentSize();
            _window = window;

            if (Event.Actions.Count > 0)
                LoadGraph();
            else
                CreateNode(new StartAction(), new Vector2(250, 250));
        }

        public override EventPropagation DeleteSelection()
        {
            foreach (var item in selection.OfType<Node>())
            {
                if (item is StartNode)
                    return EventPropagation.Stop;
            }

            MakeDirty();

            base.DeleteSelection();

            return EventPropagation.Continue;
        }

        public void CreateNode(ActionBase action, Vector2 position, string guid = null)
        {
            EventGraphNodeBase node;

            Type nodeType = _nodeTypes
                            .FirstOrDefault(type => type.BaseType.GetGenericArguments()[0] == action.GetType());


            if (nodeType is not null)
            {
                node = Activator.CreateInstance(nodeType, new object[] { action }) as EventGraphNodeBase;
            }
            else if (action.GetType().GetCustomAttribute<GenerateActionNodeAttribute>() is not null)
            {
                node = Activator.CreateInstance(typeof(AutoGeneratedNode), new object[] { action }) as AutoGeneratedNode;
            }
            else
            {
                EditorUtility.DisplayDialog("Ошибка", $"Ноды для действия {action.GetType().Name} не существует", "Ок");
                return;
            }

            node.view = this;

            node.GUID = guid ?? GUID.Generate().ToString();

            node.PortContructor();
            node.UIContructor();

            node.RefreshExpandedState();
            node.RefreshPorts();

            node.SetPosition(new Rect(position, DefaultNodeSize));

            AddElement(node);

            _window.MarkDirty();
        }

        public override List<Port> GetCompatiblePorts(Port startPort, NodeAdapter nodeAdapter)
        {
            return ports.Where(port => startPort != port && startPort.node != port.node
                                            && startPort.direction != port.direction
                                            && startPort.portType == port.portType)
                              .ToList();
        }

        public override void BuildContextualMenu(ContextualMenuPopulateEvent evt)
        {
            base.BuildContextualMenu(evt);

            Vector2 mousePosition = this.ChangeCoordinatesTo(contentViewContainer, evt.localMousePosition);

            if (evt.target is EventGraphNodeBase node)
            {
                if (node is not StartNode)
                {
                    ActionBase action = node.action.Clone();

                    evt.menu.AppendAction("Создать дубликат", i => CreateNode(action, mousePosition));
                }
            }

            foreach (var actionNodeType in _nodeTypes)
            {
                string menuPath = actionNodeType.GetCustomAttribute<UseActionNodeAttribute>().ContextualMenuPath;
                Type actionType = actionNodeType.BaseType.GetGenericArguments()[0];

                if (!string.IsNullOrEmpty(menuPath))
                {
                    evt.menu.AppendAction(
                            menuPath,
                            i => CreateNode(Activator.CreateInstance(actionType) as ActionBase,
                            mousePosition
                            ));
                }
            }

            foreach (var actionNodeType in _autoNodeTypes)
            {
                string menuPath = actionNodeType.GetCustomAttribute<GenerateActionNodeAttribute>().ContextMenuPath;

                if (!string.IsNullOrEmpty(menuPath))
                {
                    evt.menu.AppendAction(
                            menuPath,
                            i => CreateNode(Activator.CreateInstance(actionNodeType) as ActionBase,
                            mousePosition
                            ));
                }
            }
        }

        public void MakeDirty()
        {
            _window.MarkDirty();
        }

        public void SaveGraph()
        {
            Event.Meta.nodes.Clear();
            Event.Meta.edges.Clear();
            Event.Actions.Clear();

            foreach (var item in nodes)
            {
                var eventGraphNode = item as EventGraphNodeBase;

                Event.Actions.Add(eventGraphNode.action);
            }

            foreach (var item in nodes)
            {
                var eventGraphNode = item as EventGraphNodeBase;

                eventGraphNode.ValidatePorts();

                Event.Meta.nodes.Add(new GraphEventMeta.NodeMeta
                {
                    guid = eventGraphNode.GUID,
                    position = eventGraphNode.localBound.position,
                    action = eventGraphNode.action
                });
            }

            foreach (var item in edges)
            {
                var left = item.output.node as EventGraphNodeBase;
                var right = item.input.node as EventGraphNodeBase;

                if (item.input == null || item.output == null ||
                    left == null || right == null)
                    continue;

                Event.Meta.edges.Add(new GraphEventMeta.EdgeMeta
                {
                    inputNodeGUID = right.GUID,
                    outputNodeGUID = left.GUID,
                    inputPortName = item.input.portName,
                    outputPortName = item.output.portName
                });
            }

            _window.MarkDirty();

            Event.DispathGraphChanges();

            OnSaved?.Invoke();
        }

        public void LoadGraph()
        {
            foreach (var node in Event.Meta.nodes)
                CreateNode(node.action, node.position, node.guid);

            foreach (var item in Nodes)
            {
                List<GraphEventMeta.EdgeMeta> tedges = Event.Meta.edges.Where(i => i.outputNodeGUID == item.GUID).ToList();

                List<Port> tports = ports.Where(i => i.node == item && i.direction == Direction.Output).ToList();

                foreach (var port in tports)
                {
                    foreach (var edge in tedges)
                    {
                        if (port.portName != edge.outputPortName)
                            continue;

                        var ohter = Nodes.First(i => edge.inputNodeGUID == i.GUID);

                        var otherport = ports.First(i => i.node == ohter && i.portName == edge.inputPortName);

                        Edge newEdge = new()
                        {
                            input = otherport,
                            output = port
                        };

                        port.Connect(newEdge);
                        otherport.Connect(newEdge);

                        Add(newEdge);
                    }
                }
            }
        }
    }
}